# Generated by Django 3.1.2 on 2022-03-25 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tax_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('SGST', models.FloatField(default=9.0, max_length=20)),
                ('CGST', models.FloatField(default=9.0, max_length=20)),
                ('PanCard', models.CharField(max_length=12)),
                ('salaryIncome', models.IntegerField(default=0)),
                ('stockIncome', models.IntegerField(default=0)),
                ('dueDate', models.DateField(blank=True, default=tax_app.models.given_date)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('STATUS', models.CharField(default='New', max_length=10)),
                ('total_tax', models.FloatField(blank=True, default=0, max_length=10, null=True)),
                ('fines', models.IntegerField(blank=True, default=0, null=True)),
                ('paymentStatus', models.CharField(default='Unpaid', max_length=10)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
